### ISSUE TITLE
what about robustness without unlabeled data under autoattack

### ISSUE THREAD

**Issue by Equationliu** [zjfheart/Geometry-aware-Instance-reweighted-Adversarial-Training#1]

**Comment by zhangdong1992** [comment]
This method is not robust to autoattack without unlabeled data, I think it is a kind of gradient masking.

**Comment by zjfheart** [comment]
Hi, 

Many thanks for your great questions. I am sorry for the late reply. I was busy with ICML submission and holidays. 

GAIRAT training under the PGD attacks can defend PGD attacks very well, but indeed, it cannot perform well on other attacks such as the attacks you mentioned. 
From the philosophical perspective, we cannot expect defense under one specific attack can defend all existing attacks. 
This philosophy echoes the previous finding that " Our take-away VI.2. In adversarial training, it is essential to include adversarial examples produced by all known attacks, as the defensive training is non-adaptive. [1]"
One solution to this is to incorporate all existing attacks into the training procedure. 

GAIRAT actually is not quite a specific method, it is a philosophy, i.e., adversarial training should treat data differently. 

If you would like to check some specific numbers, kindly refer to our new manuscript [2]. 

[1] SoK: Towards the Science of Security and Privacy in Machine Learning. 
[2] Guided Interpolation for Adversarial training <https://arxiv.org/pdf/2102.07327.pdf>

**Comment by Equationliu** [comment]
Thank you for your detailed reply！

**Comment by zjfheart** [comment]
> This method is not robust to autoattack without unlabeled data, I think it is a kind of gradient masking.

Many thanks for your replies!
GAIRAT does not totally fails under autoattack without unlabeled data. Therefore, we cannot say this is the gradient masking.
