### ISSUE TITLE
Do you train GA with trades？

### ISSUE THREAD

**Issue by silvercherry** [zjfheart/Geometry-aware-Instance-reweighted-Adversarial-Training#4]
I notice that the work FAT has the FAT-Trades, but why this work do not train with trades?

**Comment by zjfheart** [comment]
Hi, 

You can run the code in this script for solving your concerns ./GAIR_RST/run_training.sh
RST used TRADES for learning from additional unlabeled data. 

Most importantly, the GAIRAT is a direction of methods, i.e., we should treat data differently in adversarial training. 
To make TRADES instance-dependent, you can weigh loss in KL loss or CE loss, or both in instance-dependent manner. 

Best wishes,
Jingfeng

**Comment by silvercherry** [comment]
> 

thanks for your answer. I also have an questions about the 'entropy_weight' in learning from additional unlabeled data. I notice the 'entropy_weight' is '0'; I would like to ask, why do you want to set it is ‘0’？why not subtract the unlabeled data loss ？

Best wishes

**Comment by silvercherry** [comment]
> Hi,
> 
> You can run the code in this script for solving your concerns ./GAIR_RST/run_training.sh RST used TRADES for learning from additional unlabeled data.
> 
> Most importantly, the GAIRAT is a direction of methods, i.e., we should treat data differently in adversarial training. To make TRADES instance-dependent, you can weigh loss in KL loss or CE loss, or both in instance-dependent manner.
> 
> Best wishes, Jingfeng

thanks for your answer. I also have an questions about the 'entropy_weight' in learning from additional unlabeled data. I notice the 'entropy_weight' is '0'; I would like to ask, why do you want to set it is ‘0’？why not subtract the unlabeled data loss ？

Best wishes
